### PR TITLE
Fix downloading of lerobot dataset

### PR DESCRIPTION
**Pull request by 02alexander**
Fixes issue https://github.com/rerun-io/python-example-huggingface/issues/2
Solution was found here https://huggingface.co/datasets/lerobot/pusht/discussions/2

### CODE REVIEW

**Review by jleibs — APPROVED** [review]
Is pip installing from the git url the right way to install? Is it not available as a pypi package?

**Comment by 02alexander** [comment]
lerobot exists as a package on pypi, but it's one month old and it doesn't have `lerobot.common.datasets.video_utils` which we need.

**Comment by 02alexander** [comment]
In the lerobot repository README they only mention installation via git, so I think that is the preferred option.

**Comment by 02alexander** [comment]
I discovered another problem, right now we only get the path to the video + timestamp. 
hugginface_video_file_issue

**Comment by 02alexander** [comment]
@jleibs  The lerobot datasets (version >= 1.2) are a bit complicated to download since the images are stored in a separate video files that needs to be downloaded, so I decided to let the `lerobot` package (via git) handle downloading of the dataset. One  downside of doing it this way is that `lerobot` is a huge dependency, but now it should still work even if they update how the dataset is stored.

**Comment by 02alexander** [comment]
Is it ready to be merged?

**Review by jleibs — APPROVED** [review]

**Pull request merged**
